name: Setup
description: Common setup steps used by our workflows
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
      with:
        version: 9
    - name: Setup node
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version-file: .nvmrc
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Setup foundry
      uses: foundry-rs/foundry-toolchain@8b0419c685ef46cb79ec93fbdc131174afceb730 # v1.6.0

    - name: Install node dependencies
      shell: bash
      run: pnpm install:ci
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@0e2d18b530b83b68263ff7b74e46b1ba300c83fc # v3.3.2
      with:
        main-branch-name: "develop"
    - run: |
        echo "nx using following shas:"
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"
      shell: bash
