name: Release snapshot

# Releases a snapshot release when new commits merge to develop
# This ensures the release process is working as expected as well as always gives us a release
# we should move to a single branch in near future
on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  snapshot-snapshot:
    name: Publish snapshot release to npm
    if: github.repository == 'ethereum-optimism/optimism'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Set deployment token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify NPM Token is valid
        run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish snapshots
        uses: seek-oss/changesets-snapshot@7a1b807af2b3c2c7141284c93ceeb5b5aef015dd # v0.2.0
        with:
          pre-publish: pnpm nx run-many --target=build --skip-nx-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
