name: 'Slither Analysis'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

jobs:
  slither-analyze:
    runs-on: ubuntu-latest
    container:
      image: us-docker.pkg.dev/oplabs-tools-artifacts/images/ci-builder:v0.49.0
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      # Workaround to prevent slither-action from trying to install JS deps.
      # Without this step, it detects the `package.json`, and since there is no
      # lockfile it defaults `npm install` which fails due to the preinstall
      # script to enforce pnpm. https://github.com/crytic/slither-action/issues/44#issuecomment-1338183656
      - name: Remove package.json
        run: rm packages/contracts-bedrock/package.json

      - name: Run Slither
        uses: crytic/slither-action@f197989dea5b53e986d0f88c60a034ddd77ec9a8 # v0.4.0
        id: slither
        with:
          target: packages/contracts-bedrock
          slither-config: packages/contracts-bedrock/slither.config.json
          fail-on: config
          sarif: results.sarif
          slither-args: --triage-database packages/contracts-bedrock/slither.db.json

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@192325c86100d080feab897ff886c34abd4c83a3 # v3.30.3
        if: always()
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
